extend type BusinessActivity {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "BusinessActivity", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `BusinessActivity`.`project`. It must match the value of `Project`.`id`. See `@ref` for how to customize it.
  """
  projectId: UUID @fdc_generated(from: "BusinessActivity.project", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `BusinessActivity`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: String! @fdc_generated(from: "BusinessActivity.user", purpose: IMPLICIT_REF_FIELD)
}
extend type Goal {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Goal", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Goal`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: String! @fdc_generated(from: "Goal.user", purpose: IMPLICIT_REF_FIELD)
}
extend type Project {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Project", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Project`.`goal`. It must match the value of `Goal`.`id`. See `@ref` for how to customize it.
  """
  goalId: UUID @fdc_generated(from: "Project.goal", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Project`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: String! @fdc_generated(from: "Project.user", purpose: IMPLICIT_REF_FIELD)
}
extend type Routine {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Routine", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Routine`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: String! @fdc_generated(from: "Routine.user", purpose: IMPLICIT_REF_FIELD)
}
extend type Task {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Task", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Task`.`goal`. It must match the value of `Goal`.`id`. See `@ref` for how to customize it.
  """
  goalId: UUID @fdc_generated(from: "Task.goal", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Task`.`project`. It must match the value of `Project`.`id`. See `@ref` for how to customize it.
  """
  projectId: UUID @fdc_generated(from: "Task.project", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Task`.`routine`. It must match the value of `Routine`.`id`. See `@ref` for how to customize it.
  """
  routineId: UUID @fdc_generated(from: "Task.routine", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Task`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: String! @fdc_generated(from: "Task.user", purpose: IMPLICIT_REF_FIELD)
}
