extend type Mutation {
  """
  ✨ Insert a single `BusinessActivity` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  businessActivity_insert(
    """
    Data object to insert into the table.
    """
    data: BusinessActivity_Data!
  ): BusinessActivity_KeyOutput! @fdc_generated(from: "BusinessActivity", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Goal` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  goal_insert(
    """
    Data object to insert into the table.
    """
    data: Goal_Data!
  ): Goal_KeyOutput! @fdc_generated(from: "Goal", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Project` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  project_insert(
    """
    Data object to insert into the table.
    """
    data: Project_Data!
  ): Project_KeyOutput! @fdc_generated(from: "Project", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Routine` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  routine_insert(
    """
    Data object to insert into the table.
    """
    data: Routine_Data!
  ): Routine_KeyOutput! @fdc_generated(from: "Routine", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Task` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  task_insert(
    """
    Data object to insert into the table.
    """
    data: Task_Data!
  ): Task_KeyOutput! @fdc_generated(from: "Task", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `User` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  user_insert(
    """
    Data object to insert into the table.
    """
    data: User_Data!
  ): User_KeyOutput! @fdc_generated(from: "User", purpose: INSERT_SINGLE)
  """
  ✨ Insert `BusinessActivity` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  businessActivity_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [BusinessActivity_Data!]!
  ): [BusinessActivity_KeyOutput!]! @fdc_generated(from: "BusinessActivity", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Goal` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  goal_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Goal_Data!]!
  ): [Goal_KeyOutput!]! @fdc_generated(from: "Goal", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Project` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  project_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Project_Data!]!
  ): [Project_KeyOutput!]! @fdc_generated(from: "Project", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Routine` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  routine_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Routine_Data!]!
  ): [Routine_KeyOutput!]! @fdc_generated(from: "Routine", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Task` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  task_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Task_Data!]!
  ): [Task_KeyOutput!]! @fdc_generated(from: "Task", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `User` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  user_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [User_Data!]!
  ): [User_KeyOutput!]! @fdc_generated(from: "User", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert or update a single `BusinessActivity` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `BusinessActivity`.
  """
  businessActivity_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: BusinessActivity_Data!
  ): BusinessActivity_KeyOutput! @fdc_generated(from: "BusinessActivity", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Goal` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Goal`.
  """
  goal_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Goal_Data!
  ): Goal_KeyOutput! @fdc_generated(from: "Goal", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Project` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Project`.
  """
  project_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Project_Data!
  ): Project_KeyOutput! @fdc_generated(from: "Project", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Routine` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Routine`.
  """
  routine_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Routine_Data!
  ): Routine_KeyOutput! @fdc_generated(from: "Routine", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Task` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Task`.
  """
  task_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Task_Data!
  ): Task_KeyOutput! @fdc_generated(from: "Task", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `User` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `User`.
  """
  user_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: User_Data!
  ): User_KeyOutput! @fdc_generated(from: "User", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update `BusinessActivity` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `BusinessActivity`.
  """
  businessActivity_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [BusinessActivity_Data!]!
  ): [BusinessActivity_KeyOutput!]! @fdc_generated(from: "BusinessActivity", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Goal` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Goal`.
  """
  goal_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Goal_Data!]!
  ): [Goal_KeyOutput!]! @fdc_generated(from: "Goal", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Project` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Project`.
  """
  project_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Project_Data!]!
  ): [Project_KeyOutput!]! @fdc_generated(from: "Project", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Routine` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Routine`.
  """
  routine_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Routine_Data!]!
  ): [Routine_KeyOutput!]! @fdc_generated(from: "Routine", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Task` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Task`.
  """
  task_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Task_Data!]!
  ): [Task_KeyOutput!]! @fdc_generated(from: "Task", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `User` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `User`.
  """
  user_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [User_Data!]!
  ): [User_KeyOutput!]! @fdc_generated(from: "User", purpose: UPSERT_MULTIPLE)
  """
  ✨ Update a single `BusinessActivity` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `BusinessActivity` or `null` if not found.
  """
  businessActivity_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: BusinessActivity_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: BusinessActivity_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: BusinessActivity_Data!
  ): BusinessActivity_KeyOutput @fdc_generated(from: "BusinessActivity", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Goal` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Goal` or `null` if not found.
  """
  goal_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Goal_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Goal_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Goal_Data!
  ): Goal_KeyOutput @fdc_generated(from: "Goal", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Project` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Project` or `null` if not found.
  """
  project_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Project_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Project_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Project_Data!
  ): Project_KeyOutput @fdc_generated(from: "Project", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Routine` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Routine` or `null` if not found.
  """
  routine_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Routine_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Routine_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Routine_Data!
  ): Routine_KeyOutput @fdc_generated(from: "Routine", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Task` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Task` or `null` if not found.
  """
  task_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Task_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Task_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Task_Data!
  ): Task_KeyOutput @fdc_generated(from: "Task", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `User` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `User` or `null` if not found.
  """
  user_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: User_Data!
  ): User_KeyOutput @fdc_generated(from: "User", purpose: UPDATE_SINGLE)
  """
  ✨ Update `BusinessActivity` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  businessActivity_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: BusinessActivity_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: BusinessActivity_Data!
  ): Int! @fdc_generated(from: "BusinessActivity", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Goal` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  goal_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Goal_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Goal_Data!
  ): Int! @fdc_generated(from: "Goal", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Project` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  project_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Project_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Project_Data!
  ): Int! @fdc_generated(from: "Project", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Routine` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  routine_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Routine_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Routine_Data!
  ): Int! @fdc_generated(from: "Routine", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Task` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  task_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Task_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Task_Data!
  ): Int! @fdc_generated(from: "Task", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `User` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  user_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: User_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: User_Data!
  ): Int! @fdc_generated(from: "User", purpose: UPDATE_MULTIPLE)
  """
  ✨ Delete a single `BusinessActivity` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  businessActivity_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: BusinessActivity_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: BusinessActivity_FirstRow
  ): BusinessActivity_KeyOutput @fdc_generated(from: "BusinessActivity", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Goal` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  goal_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Goal_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Goal_FirstRow
  ): Goal_KeyOutput @fdc_generated(from: "Goal", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Project` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  project_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Project_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Project_FirstRow
  ): Project_KeyOutput @fdc_generated(from: "Project", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Routine` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  routine_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Routine_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Routine_FirstRow
  ): Routine_KeyOutput @fdc_generated(from: "Routine", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Task` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  task_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Task_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Task_FirstRow
  ): Task_KeyOutput @fdc_generated(from: "Task", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `User` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  user_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow
  ): User_KeyOutput @fdc_generated(from: "User", purpose: DELETE_SINGLE)
  """
  ✨ Delete `BusinessActivity` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  businessActivity_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: BusinessActivity_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "BusinessActivity", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Goal` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  goal_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Goal_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Goal", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Project` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  project_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Project_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Project", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Routine` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  routine_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Routine_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Routine", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Task` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  task_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Task_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Task", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `User` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  user_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: User_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "User", purpose: DELETE_MULTIPLE)
}
