extend type BusinessActivity {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "BusinessActivity", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `BusinessActivity` table.
  """
  _count: Int! @fdc_generated(from: "BusinessActivity.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `BusinessActivity` table where the `activityDate` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  activityDate_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "BusinessActivity.activityDate", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `BusinessActivity` table where the `amount` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  amount_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "BusinessActivity.amount", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `BusinessActivity` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "BusinessActivity.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `BusinessActivity` table where the `description` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  description_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "BusinessActivity.description", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `BusinessActivity` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "BusinessActivity.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `BusinessActivity` table where the `projectId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  projectId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "BusinessActivity.projectId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `BusinessActivity` table where the `relatedClient` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  relatedClient_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "BusinessActivity.relatedClient", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `BusinessActivity` table where the `status` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  status_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "BusinessActivity.status", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `BusinessActivity` table where the `type` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  type_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "BusinessActivity.type", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `BusinessActivity` table where the `userId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  userId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "BusinessActivity.userId", purpose: QUERY_COUNT)
  """
  ✨ Sum the `amount` field in the `BusinessActivity` table.
  """
  amount_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "BusinessActivity.amount", purpose: QUERY_SUM)
  """
  ✨ Average the `amount` field in the `BusinessActivity` table.
  """
  amount_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "BusinessActivity.amount", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `activityDate` field in the `BusinessActivity` table.
  """
  activityDate_min: Date @fdc_generated(from: "BusinessActivity.activityDate", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `amount` field in the `BusinessActivity` table.
  """
  amount_min: Float @fdc_generated(from: "BusinessActivity.amount", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `createdAt` field in the `BusinessActivity` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "BusinessActivity.createdAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `activityDate` field in the `BusinessActivity` table.
  """
  activityDate_max: Date @fdc_generated(from: "BusinessActivity.activityDate", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `amount` field in the `BusinessActivity` table.
  """
  amount_max: Float @fdc_generated(from: "BusinessActivity.amount", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `createdAt` field in the `BusinessActivity` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "BusinessActivity.createdAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "BusinessActivity.id", purpose: GLOBAL_ID)
}
extend type Goal {
  """
  ✨ List `Project` objects in a one-to-many relationship (where `Project`.`goal` is this object).
  """
  projects_on_goal(
    """
    Filter condition to narrow down the query results.
    """
    where: Project_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Project_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Project_Having
  ): [Project!]! @fdc_generated(from: "Project.goal", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `Task` objects in a one-to-many relationship (where `Task`.`goal` is this object).
  """
  tasks_on_goal(
    """
    Filter condition to narrow down the query results.
    """
    where: Task_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Task_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Task_Having
  ): [Task!]! @fdc_generated(from: "Task.goal", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Goal", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Goal` table.
  """
  _count: Int! @fdc_generated(from: "Goal.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Goal` table where the `category` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  category_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Goal.category", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Goal` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Goal.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Goal` table where the `description` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  description_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Goal.description", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Goal` table where the `dueDate` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  dueDate_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Goal.dueDate", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Goal` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Goal.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Goal` table where the `status` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  status_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Goal.status", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Goal` table where the `title` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  title_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Goal.title", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Goal` table where the `userId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  userId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Goal.userId", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `createdAt` field in the `Goal` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "Goal.createdAt", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `dueDate` field in the `Goal` table.
  """
  dueDate_min: Date @fdc_generated(from: "Goal.dueDate", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `Goal` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "Goal.createdAt", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `dueDate` field in the `Goal` table.
  """
  dueDate_max: Date @fdc_generated(from: "Goal.dueDate", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Goal.id", purpose: GLOBAL_ID)
}
extend type Project {
  """
  ✨ List `BusinessActivity` objects in a one-to-many relationship (where `BusinessActivity`.`project` is this object).
  """
  businessActivities_on_project(
    """
    Filter condition to narrow down the query results.
    """
    where: BusinessActivity_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [BusinessActivity_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: BusinessActivity_Having
  ): [BusinessActivity!]! @fdc_generated(from: "BusinessActivity.project", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `Task` objects in a one-to-many relationship (where `Task`.`project` is this object).
  """
  tasks_on_project(
    """
    Filter condition to narrow down the query results.
    """
    where: Task_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Task_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Task_Having
  ): [Task!]! @fdc_generated(from: "Task.project", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Project", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Project` table.
  """
  _count: Int! @fdc_generated(from: "Project.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Project` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Project.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Project` table where the `description` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  description_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Project.description", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Project` table where the `endDate` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  endDate_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Project.endDate", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Project` table where the `goalId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  goalId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Project.goalId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Project` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Project.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Project` table where the `name` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  name_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Project.name", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Project` table where the `startDate` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  startDate_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Project.startDate", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Project` table where the `status` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  status_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Project.status", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Project` table where the `userId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  userId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Project.userId", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `createdAt` field in the `Project` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "Project.createdAt", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `endDate` field in the `Project` table.
  """
  endDate_min: Date @fdc_generated(from: "Project.endDate", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `startDate` field in the `Project` table.
  """
  startDate_min: Date @fdc_generated(from: "Project.startDate", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `Project` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "Project.createdAt", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `endDate` field in the `Project` table.
  """
  endDate_max: Date @fdc_generated(from: "Project.endDate", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `startDate` field in the `Project` table.
  """
  startDate_max: Date @fdc_generated(from: "Project.startDate", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Project.id", purpose: GLOBAL_ID)
}
extend type Routine {
  """
  ✨ List `Task` objects in a one-to-many relationship (where `Task`.`routine` is this object).
  """
  tasks_on_routine(
    """
    Filter condition to narrow down the query results.
    """
    where: Task_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Task_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Task_Having
  ): [Task!]! @fdc_generated(from: "Task.routine", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Routine", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Routine` table.
  """
  _count: Int! @fdc_generated(from: "Routine.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Routine` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Routine.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Routine` table where the `description` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  description_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Routine.description", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Routine` table where the `endTime` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  endTime_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Routine.endTime", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Routine` table where the `frequency` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  frequency_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Routine.frequency", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Routine` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Routine.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Routine` table where the `name` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  name_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Routine.name", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Routine` table where the `startTime` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  startTime_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Routine.startTime", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Routine` table where the `userId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  userId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Routine.userId", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `createdAt` field in the `Routine` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "Routine.createdAt", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `endTime` field in the `Routine` table.
  """
  endTime_min: Timestamp @fdc_generated(from: "Routine.endTime", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `startTime` field in the `Routine` table.
  """
  startTime_min: Timestamp @fdc_generated(from: "Routine.startTime", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `Routine` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "Routine.createdAt", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `endTime` field in the `Routine` table.
  """
  endTime_max: Timestamp @fdc_generated(from: "Routine.endTime", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `startTime` field in the `Routine` table.
  """
  startTime_max: Timestamp @fdc_generated(from: "Routine.startTime", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Routine.id", purpose: GLOBAL_ID)
}
extend type Task {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Task", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Task` table.
  """
  _count: Int! @fdc_generated(from: "Task.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Task` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Task.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Task` table where the `description` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  description_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Task.description", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Task` table where the `dueDate` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  dueDate_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Task.dueDate", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Task` table where the `goalId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  goalId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Task.goalId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Task` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Task.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Task` table where the `priority` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  priority_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Task.priority", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Task` table where the `projectId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  projectId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Task.projectId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Task` table where the `routineId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  routineId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Task.routineId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Task` table where the `status` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  status_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Task.status", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Task` table where the `userId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  userId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Task.userId", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `createdAt` field in the `Task` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "Task.createdAt", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `dueDate` field in the `Task` table.
  """
  dueDate_min: Date @fdc_generated(from: "Task.dueDate", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `Task` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "Task.createdAt", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `dueDate` field in the `Task` table.
  """
  dueDate_max: Date @fdc_generated(from: "Task.dueDate", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Task.id", purpose: GLOBAL_ID)
}
extend type User {
  """
  ✨ List `BusinessActivity` objects in a one-to-many relationship (where `BusinessActivity`.`user` is this object).
  """
  businessActivities_on_user(
    """
    Filter condition to narrow down the query results.
    """
    where: BusinessActivity_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [BusinessActivity_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: BusinessActivity_Having
  ): [BusinessActivity!]! @fdc_generated(from: "BusinessActivity.user", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `Goal` objects in a one-to-many relationship (where `Goal`.`user` is this object).
  """
  goals_on_user(
    """
    Filter condition to narrow down the query results.
    """
    where: Goal_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Goal_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Goal_Having
  ): [Goal!]! @fdc_generated(from: "Goal.user", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `Project` objects in a one-to-many relationship (where `Project`.`user` is this object).
  """
  projects_on_user(
    """
    Filter condition to narrow down the query results.
    """
    where: Project_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Project_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Project_Having
  ): [Project!]! @fdc_generated(from: "Project.user", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `Routine` objects in a one-to-many relationship (where `Routine`.`user` is this object).
  """
  routines_on_user(
    """
    Filter condition to narrow down the query results.
    """
    where: Routine_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Routine_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Routine_Having
  ): [Routine!]! @fdc_generated(from: "Routine.user", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `Task` objects in a one-to-many relationship (where `Task`.`user` is this object).
  """
  tasks_on_user(
    """
    Filter condition to narrow down the query results.
    """
    where: Task_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Task_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Task_Having
  ): [Task!]! @fdc_generated(from: "Task.user", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "User", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `User` table.
  """
  _count: Int! @fdc_generated(from: "User.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `bio` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  bio_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.bio", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `culturalAffiliation` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  culturalAffiliation_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.culturalAffiliation", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `displayName` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  displayName_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.displayName", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `email` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  email_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.email", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `photoUrl` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  photoUrl_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.photoUrl", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `createdAt` field in the `User` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "User.createdAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `User` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "User.createdAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "User.id", purpose: GLOBAL_ID)
}
